version: '3'
services:

  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: "${PROJECT}-frontend"
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./frontend:/app
    networks:
      - appnet


networks:
  appnet:
    name: appnet
    driver: bridge
    external: true
